device: "cpu"
env_name: "CartPole"

seed: 0
use_seed: False

human_render: False
render_per_epoch: False

num_epochs: 50
batch_size: 5000
num_eval_episodes: 1
train_pi_iters: 80
train_v_iters: 80

hidden_dims: [64,64]
activation: "tanh"
output_activation: "identity"

pi_lr: 3e-4
vf_lr: 1e-3
gamma: 0.99
lam: 0.97

clip_ratio: 0.2
target_kl: 0.01

output_dir: "output"
hparams_path: "hparams.json"
checkpoint_path: "checkpoint.pkl"
results_path: "results.pkl"

